# Generated by Django 3.0.3 on 2020-04-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeaEMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hechosreporteemsinee',
            table=None,
        ),
    ]
