# Generated by Django 3.0.4 on 2020-04-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeaEMS', '0003_auto_20200402_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadesFederativas',
            fields=[
                ('ipkentidad_federativa', models.IntegerField(db_column='iPkEntidadFederativa', primary_key=True, serialize=False)),
                ('clave_entidad', models.CharField(blank=True, db_column='cClaveEntidad', max_length=256, null=True)),
                ('clave_nombre_entidad', models.CharField(blank=True, db_column='cNombreEntidad', max_length=256, null=True)),
            ],
            options={
                'db_table': 'entidadesFederativas',
                'db_tablespace': 'dimensionesPlaneaEms',
                'managed': False,
            },
        ),
    ]
