# Generated by Django 3.0.4 on 2020-04-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeaEMS', '0004_article_reporter'),
        ('planeaEMS', '0004_entidadesfederativas'),
    ]

    operations = [
    ]
